Repository HackYourFuture-CPH/Guide-IT, pull requests merged in 2021-06, with the labels that each got.

#227 Change seeding for answers table
  src/server/seeds/development/02_answers.js
  src/server/seeds/production/02_answers.js
Labels: databases

#224 added profile button to home page if user logged in
  src/client/components/LeftBlueBar/LeftBlueBar.component.js
  src/client/containers/ProfilePage/ProfilePage.container.js
Labels: frontend

#230 Change production seeding
  src/server/seeds/production/01_questions.js
Labels: databases

#233 removed up and down arrow images and added css for the elevator compo…
  src/client/components/Elevator/Elevator.component.js
  src/client/components/Elevator/Elevator.styles.css
  src/client/components/ElevatorPitchInstructions/ElevatorPitchInstructions.component.js
  src/client/components/ElevatorPitchInstructions/ElevatorPitchInstructions.styles.css
  src/client/components/RoboModal/RoboModal.component.js
  src/client/components/RoboModal/RoboModal.styles.css
Labels: frontend

#232 Fixed next step page stylings
  src/client/containers/NextStepsPage/NextStepsPage.container.js
  src/client/containers/NextStepsPage/NextStepsPage.styles.css
Labels: frontend

#226 made side menu look similar in all pages
  src/client/components/SideMenu/SideMenu.styles.css
  src/client/containers/ElevatorPitchPage/ElevatorPitchPage.styles.css
  src/client/containers/EmptyQuizResultPage/EmptyQuizResultPage.styles.css
  src/client/containers/Home/Home.styles.css
  src/client/containers/QuizPage/QuizPage.styles.css
Labels: frontend

#221 Added auth.currentUser check
  src/client/containers/ProfilePage/ProfilePage.container.js
  src/client/containers/QuizPage/QuizPage.container.js
Labels: frontend

#237 changed the button styles and added border and space to the login text
  src/client/components/LeftBlueBar/LeftBlueBar.component.js
  src/client/components/LeftBlueBar/LeftBlueBar.styles.css
  src/client/containers/Home/Home.styles.css
Labels: frontend

#236 CSS changes to quiz-page container
  src/client/components/QuizAnswers/QuizAnswers.component.js
  src/client/components/QuizAnswers/QuizAnswers.styles.css
  src/client/containers/QuizPage/QuizPage.styles.css
Labels: frontend

#235 added shadows for homepage header and homepage buttons
  src/client/components/HomepageHeader/header.styles.css
  src/client/containers/Home/Home.styles.css
Labels: frontend

#234 Change postbuild script to avoid seeding every build
  package.json
Labels: deployment

#239 Merge develop into master
  package.json
  src/client/components/Elevator/Elevator.component.js
  src/client/components/Elevator/Elevator.styles.css
  src/client/components/ElevatorPitchInstructions/ElevatorPitchInstructions.component.js
  src/client/components/ElevatorPitchInstructions/ElevatorPitchInstructions.styles.css
  src/client/components/HomepageHeader/header.styles.css
  src/client/components/LeftBlueBar/LeftBlueBar.component.js
  src/client/components/LeftBlueBar/LeftBlueBar.styles.css
  src/client/components/Question/Question.styles.css
  src/client/components/QuizAnswers/QuizAnswers.component.js
  src/client/components/QuizAnswers/QuizAnswers.styles.css
  src/client/components/RoboModal/RoboModal.component.js
  src/client/components/RoboModal/RoboModal.styles.css
  src/client/components/SideMenu/SideMenu.styles.css
  src/client/containers/ElevatorPitchPage/ElevatorPitchPage.styles.css
  src/client/containers/EmptyQuizResultPage/EmptyQuizResultPage.styles.css
  src/client/containers/Home/Home.styles.css
  src/client/containers/NextStepsPage/NextStepsPage.container.js
  src/client/containers/NextStepsPage/NextStepsPage.styles.css
  src/client/containers/ProfilePage/ProfilePage.container.js
  src/client/containers/QuizPage/QuizPage.container.js
  src/client/containers/QuizPage/QuizPage.styles.css
Labels: deployment
