Repository HackYourFuture-CPH/Guide-IT, pull requests merged in 2021-05, with the labels that each got.

#92 changed package.json and .gitignore to make the storybook deployment
  .gitignore
  package-lock.json
  package.json
Labels: deployment, storybook

#77 Seeding questions table
  src/server/seeds/development/01_questions.js
  src/server/seeds/development/modules.js
Labels: databases

#79 renamed create_questions_schema.js -> 20210427152901_create_questions…
  src/server/migrations/20210427152901_create_questions_table.js
Labels: databases

#83 added migration answers table
  src/server/migrations/20210427212734_answers_table.js
Labels: databases

#86 I created users table migration
  src/server/migrations/20210428000652_create_users_table.js
Labels: databases

#80 deleted uneccessary font link in index.css, because there is an alrea…
  src/client/components/RobotLogo/RobotLogo.css
  src/client/components/sideMenubar/sideMenu.styles.css
  src/client/index.css
Labels: frontend

#84 deleted extra envelope image and made changes in emailregistration fo…
  src/client/assets/images/envelop.png
  src/client/components/EmailRegistration/EmailForm.css
Labels: frontend

#98 altered the foreign key for answers table to fix the error
  src/server/migrations/20210502135612_answers_table.js
Labels: databases

#78 Create migrations for quiz results table without fk
  src/server/migrations/20210502145305_quiz_results_table.js
Labels: databases

#76 Quiz Result page is ready for reviews
  src/client/assets/images/Vector.svg
  src/client/components/RegisterTeaser/RegisterTeaser.css
  src/client/containers/QuizResultPage/QuizResultPage.component.js
  src/client/containers/QuizResultPage/QuizResultPage.stories.js
  src/client/containers/QuizResultPage/QuizResultPage.styles.css
Labels: frontend, storybook

#99 typo chage
  src/client/components/sideMenubar/sideMenu.js
Labels: frontend

#85 I changed the classname from small to small-button
  src/client/components/Buttons/Buttons.js
  src/client/components/Buttons/Buttons.stories.js
  src/client/components/Buttons/Buttons.styles.css
Labels: frontend, storybook

#112 added the seeding for answers table
  src/server/seeds/development/02_answers.js
Labels: databases

#115 deleted unnecessary font link
  src/client/components/PageHeaderComponent/PageHeader.styles.css
Labels: frontend

#119 POST endpoint for api/quiz-results
  src/server/api/controllers/quiz_results.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/quiz_results.router.js
Labels: backend

#95 Add script to run migratation
  package.json
Labels: deployment

#120 Created POST endpoint for users table
  src/server/api/controllers/users.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/users.router.js
Labels: backend

#126 Responsive Quize Result Page
  src/client/components/CardProfileResult/CardProfileResultComponent.styles.css
  src/client/containers/QuizResultPage/QuizResultPage.styles.css
Labels: frontend

#130 add registration page container storybook component
  src/client/assets/images/arrow_back.png
  src/client/containers/RegistrationPage/RegistrationPage.component.js
  src/client/containers/RegistrationPage/RegistrationPage.stories.js
  src/client/containers/RegistrationPage/RegistrationPage.styles.css
Labels: frontend, storybook

#124 Homepage/container
  src/client/App.js
  src/client/containers/Home/Home.css
  src/client/containers/Home/Home.js
Labels: frontend

#125 Changed some CSS for responsiveness and added link to the button
  src/client/containers/404Page/404Page.container.js
  src/client/containers/404Page/404Page.styles.css
Labels: frontend

#129 buttons work for 5 pages and make some changes in css for responsive
  src/client/containers/QuizPage/QuizPage.component.js
  src/client/containers/QuizPage/QuizPage.styles.css
Labels: frontend

#116 Endpoint for GET Users
  src/server/api/controllers/users.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/users.router.js
Labels: backend

#121 Add endpoint to retrieve quiz results
  src/server/api/controllers/quiz-results.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/quiz-results.router.js
Labels: backend

#123 POST endpoint api/questions
  src/server/api/controllers/questions.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/questions.router.js
Labels: backend

#131 i have changed the css for career page responsiveness
  src/client/components/ResultJobFeatures/ResultJobFeatures.styles.css
  src/client/containers/CareerPage/CareerPage.component.js
  src/client/containers/CareerPage/CareerPage.styles.css
Labels: frontend

#128 Swagger answers endpoit
  src/server/api/controllers/answers.controller.js
  src/server/api/routes/answers.router.js
  src/server/api/routes/api-router.js
Labels: backend

#134 rename files acording to the guidelines and fix storybook errors rela…
  src/client/App.js
  src/client/components/Auth/AuthenticatedRoute.component.js
  src/client/components/Buttons/Buttons.component.js
  src/client/components/Buttons/Buttons.stories.js
  src/client/components/CardProfileResult/CardProfileResult.component.js
  src/client/components/CardProfileResult/CardProfileResult.stories.js
  src/client/components/CardProfileResult/CardProfileResult.styles.css
  src/client/components/PageHeader/PageHeader.component.js
  src/client/components/PageHeader/PageHeader.stories.js
  src/client/components/PageHeader/PageHeader.styles.css
  src/client/components/ProgressBar/ProgressBar.component.js
  src/client/components/ProgressBar/ProgressBar.stories.js
  src/client/components/ProgressBar/ProgressBar.styles.css
  src/client/components/Question/Question.component.js
  src/client/components/Question/Question.stories.js
  src/client/components/Question/Question.styles.css
  src/client/components/QuizAnswers/QuizAnswers.component.js
  src/client/components/QuizAnswers/QuizAnswers.stories.js
  src/client/components/RegisterTeaser/RegisterTeaser.component.js
  src/client/components/RegisterTeaser/RegisterTeaser.stories.js
  src/client/components/RegisterTeaser/RegisterTeaser.styles.css
  src/client/components/RobotLogo/RobotLogo.component.js
  src/client/components/RobotLogo/RobotLogo.stories.js
  src/client/components/RobotLogo/RobotLogo.styles.css
  src/client/components/SideMenu/SideMenu.component.js
  src/client/components/SideMenu/SideMenu.stories.js
  src/client/components/SideMenu/SideMenu.styles.css
  src/client/containers/CareerPage/CareerPage.component.js
  src/client/containers/EmptyQuizResultPage/EmptyQuizResultPage.container.js
  src/client/containers/Home/Home.js
  src/client/containers/QuizPage/QuizPage.component.js
  src/client/containers/QuizResultPage/QuizResultPage.component.js
Labels: frontend

#113 GET api route for all questions and questions by id
  .eslintrc.js
  src/server/api/controllers/questions.controller.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/questions.router.js
  src/server/api/routes/users.router.js
Labels: backend

#135 Drop foreign keys for tables to fix heroku build
  src/server/seeds/development/01_questions.js
Labels: databases

#133 merged 2 different files for quiz_results and syntax error on users.router
  src/server/api/controllers/quiz-results.controller.js
  src/server/api/controllers/quiz_results.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/quiz-results.router.js
  src/server/api/routes/quiz_results.router.js
  src/server/api/routes/users.router.js
Labels: backend

#139 fixed files that don't follow naming convention fourth PR
  src/client/App.js
  src/client/components/DecriptionHome/DescriptionCareer.component.js
  src/client/components/DecriptionHome/DescriptionCareer.stories.js
  src/client/components/DecriptionHome/DescriptionCareer.styles.css
  src/client/components/EmailRegistration/EmailForm.component.js
  src/client/components/EmailRegistration/EmailForm.stories.js
  src/client/components/EmailRegistration/EmailForm.styles.css
  src/client/components/GoogleLoginButton/GoogleLoginButton.component.js
  src/client/components/GoogleLoginButton/GoogleLoginButton.stories.js
  src/client/components/GoogleLoginButton/GoogleLoginButton.styles.css
  src/client/components/HomeDescription/HomeDescription.component.js
  src/client/components/HomeDescription/HomeDescription.stories.js
  src/client/components/HomepageHeader/Header.component.js
  src/client/components/HomepageHeader/Header.stories.js
  src/client/components/HomepageHeader/header.styles.css
  src/client/components/JobCard/JobCard.component.js
  src/client/components/JobCard/JobCard.stories.js
  src/client/components/LeftBlueBar/LeftBlueBar.component.js
  src/client/components/LeftBlueBar/LeftBlueBar.stories.js
  src/client/components/LeftBlueBar/LeftBlueBar.styles.css
  src/client/components/Modal/Modal.component.js
  src/client/components/Modal/Modal.stories.js
  src/client/components/Modal/Modal.styles.css
  src/client/components/ProfileForm/ProfileForm.component.js
  src/client/components/ProfileForm/ProfileForm.stories.js
  src/client/components/ProfileForm/ProfileForm.styles.css
  src/client/components/ResultJobFeatures/ResultJobFeatures.component.js
  src/client/components/ResultJobFeatures/ResultJobFeatures.stories.js
  src/client/components/Sample/Sample.component.js
  src/client/components/Sample/Sample.stories.js
  src/client/components/Sample/Sample.styles.css
  src/client/containers/CareerPage/CareerPage.component.js
  src/client/containers/Home/Home.container.js
  src/client/containers/Home/Home.styles.css
  src/client/containers/Home/Home.test.js
  src/client/containers/RegistrationPage/RegistrationPage.component.js
Labels: frontend

#141 Homepage responsiveness
  src/client/containers/Home/Home.container.js
  src/client/containers/Home/Home.styles.css
Labels: frontend

#145 Profile quiz results
  src/client/components/ProfileQuizResults/ProfileQuizResults.component.js
  src/client/components/ProfileQuizResults/ProfileQuizResults.stories.js
  src/client/components/ProfileQuizResults/ProfileQuizResults.styles.css
Labels: frontend

#146 Emailform responsiveness
  src/client/components/EmailRegistration/EmailForm.component.js
  src/client/components/EmailRegistration/EmailForm.stories.js
  src/client/components/EmailRegistration/EmailForm.styles.css
Labels: frontend

#140 I have added all the routes for missing pages
  src/client/App.js
Labels: frontend

#143 responsive for registration input
  src/client/containers/RegistrationPage/RegistrationPage.component.js
Labels: frontend

#144 get by user id api/quiz-results modify
  src/server/api/controllers/quiz-results.controller.js
Labels: backend

#148 get answer by id api/anwers modify
  src/server/api/controllers/answers.controller.js
Labels: backend

#151 Elevator pitch instruction
  src/client/assets/images/down_arrow.png
  src/client/assets/images/elevator_men.png
  src/client/assets/images/up_arrow.png
  src/client/components/ElevatorPitchInstructions/ElevatorPitchInstructions.component.js
  src/client/components/ElevatorPitchInstructions/ElevatorPitchInstructions.stories.js
  src/client/components/ElevatorPitchInstructions/ElevatorPitchInstructions.styles.css
Labels: frontend

#155 POST quiz result
  src/server/api/controllers/quiz-results.controller.js
  src/server/api/routes/quiz-results.router.js
Labels: backend

#156 Anonymous user for quiz results
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
Labels: backend

#150 next steps page added
  src/client/assets/images/Next_page_imgs/cf.png
  src/client/assets/images/Next_page_imgs/coursera.png
  src/client/assets/images/Next_page_imgs/linkedinLearn.png
  src/client/assets/images/Next_page_imgs/lynda.png
  src/client/assets/images/Next_page_imgs/round.png
  src/client/assets/images/Next_page_imgs/udacity.png
  src/client/assets/images/Next_page_imgs/udemy.png
  src/client/containers/NextStepsPage/NextStepsPage.component.js
  src/client/containers/NextStepsPage/NextStepsPage.stories.js
  src/client/containers/NextStepsPage/NextStepsPage.styles.css
Labels: frontend

#158 Improve css for profile_quiz_results
  src/client/components/ProfileQuizResults/ProfileQuizResults.component.js
  src/client/components/ProfileQuizResults/ProfileQuizResults.styles.css
Labels: frontend

#154 Profile Career Results Component
  src/client/components/ProfileCareerResult/ProfileCareerResult.component.js
  src/client/components/ProfileCareerResult/ProfileCareerResult.stories.js
  src/client/components/ProfileCareerResult/ProfileCareerResult.styles.css
Labels: frontend

#160 remove unnecessary files
  src/client/components/Sample/Sample.component.js
  src/client/components/Sample/Sample.stories.js
  src/client/components/Sample/Sample.styles.css
  src/server/api/controllers/modules.controller.js
  src/server/api/routes/modules.router.js
  src/server/migrations/20200510015322_create_modules_schema.js
Labels: frontend

#142 Links functionality to pages of (login) and (create account) for the homepage is added
  src/client/components/LeftBlueBar/LeftBlueBar.component.js
  src/client/components/LeftBlueBar/LeftBlueBar.styles.css
Labels: frontend

#161 Renaming the Classnames according to the name conventions
  src/client/components/DecriptionHome/DescriptionCareer.component.js
  src/client/components/DecriptionHome/DescriptionCareer.styles.css
  src/client/components/EmailRegistration/EmailForm.component.js
  src/client/components/EmailRegistration/EmailForm.styles.css
  src/client/components/GoogleLoginButton/GoogleLoginButton.component.js
  src/client/components/GoogleLoginButton/GoogleLoginButton.styles.css
  src/client/components/ProfileForm/ProfileForm.component.js
  src/client/components/ProfileForm/ProfileForm.styles.css
  src/client/components/ProfileQuizResults/ProfileQuizResults.component.js
  src/client/components/ProfileQuizResults/ProfileQuizResults.styles.css
  src/client/components/QuizAnswers/QuizAnswers.component.js
  src/client/components/QuizAnswers/QuizAnswers.styles.css
  src/client/components/SideMenu/SideMenu.component.js
  src/client/components/SideMenu/SideMenu.styles.css
  src/client/containers/EmptyQuizResultPage/EmptyQuizResultPage.container.js
  src/client/containers/EmptyQuizResultPage/EmptyQuizResultPage.styles.css
  src/client/containers/Home/Home.styles.css
  src/client/containers/NextStepsPage/NextStepsPage.component.js
  src/client/containers/NextStepsPage/NextStepsPage.styles.css
  src/client/containers/QuizPage/QuizPage.component.js
  src/client/containers/QuizPage/QuizPage.styles.css
  src/client/containers/QuizResultPage/QuizResultPage.styles.css
  src/client/containers/RegistrationPage/RegistrationPage.component.js
  src/client/containers/RegistrationPage/RegistrationPage.styles.css
Labels: frontend

#163 Delete modules from api-router
  src/server/api/routes/api-router.js
Labels: backend

#165 fixed buttons at home page not showing at some screen resolutions
  src/client/containers/QuizPage/QuizPage.styles.css
Labels: frontend

#167 fixed quiz page link
  src/client/containers/Home/Home.container.js
Labels: frontend

#166 added profile side blue bar storybook component
  src/client/assets/images/profile_back_arrow.png
  src/client/components/ProfileBlueBar/ProfileBlueBar.component.js
  src/client/components/ProfileBlueBar/ProfileBlueBar.stories.js
  src/client/components/ProfileBlueBar/ProfileBlueBar.styles.css
Labels: frontend

#149 added the files for burger menu
  src/client/components/LeftBlueBar/LeftBlueBar.component.js
  src/client/components/LeftBlueBar/LeftBlueBar.styles.css
  src/client/containers/Home/Home.styles.css
Labels: frontend

#153 Pagination
  src/client/assets/fonts/fonts.css
  src/client/assets/fonts/wellfleet-v10-latin-regular.eot
  src/client/assets/fonts/wellfleet-v10-latin-regular.svg
  src/client/assets/fonts/wellfleet-v10-latin-regular.ttf
  src/client/assets/fonts/wellfleet-v10-latin-regular.woff
  src/client/assets/fonts/wellfleet-v10-latin-regular.woff2
  src/client/components/Pagination/Pagination.component.js
  src/client/components/Pagination/Pagination.stories.js
  src/client/components/Pagination/Pagination.styles.css
Labels: frontend

#168 added two columns in questions table
  src/server/migrations/20210520221859_alter_questions_table.js
Labels: databases

#174 Link and Router is added instead of <a> tag.
  src/client/components/LeftBlueBar/LeftBlueBar.component.js
Labels: frontend

#173 added elevator component, without pagination(for now)
  src/client/components/Elevator/Elevator.component.js
  src/client/components/Elevator/Elevator.stories.js
  src/client/components/Elevator/Elevator.styles.css
Labels: frontend

#162 create end points for post and delete answer
  src/server/api/controllers/answers.controller.js
  src/server/api/routes/answers.router.js
Labels: backend

#180 added one line to center the pagination inside Elevator component
  src/client/components/Pagination/Pagination.styles.css
Labels: frontend

#175 added image_url and is_agreement_question
  src/server/seeds/development/01_questions.js
Labels: databases

#152 Career result
  src/client/App.js
  src/client/components/RegisterTeaser/RegisterTeaser.component.js
  src/client/components/RegisterTeaser/RegisterTeaser.styles.css
  src/client/components/RobotLogo/RobotLogo.component.js
  src/client/components/RobotLogo/RobotLogo.styles.css
  src/client/containers/CareerPage/CareerPage.component.js
  src/client/containers/QuizResultPage/QuizResultPage.component.js
  src/client/containers/QuizResultPage/quizResultGetCareer.apiRequest.js
Labels: frontend

#164 fixed home container fontSize and descriptionCareer proptypes error
  src/client/components/DecriptionHome/DescriptionCareer.component.js
  src/client/containers/Home/Home.container.js
Labels: frontend

#178 Profilepage/storybook
  src/client/containers/ProfilePage/ProfilePage.component.js
  src/client/containers/ProfilePage/ProfilePage.container.js
  src/client/containers/ProfilePage/ProfilePage.stories.js
  src/client/containers/ProfilePage/ProfilePage.styles.css
Labels: frontend

#179 removed unused import from reactRouterDom
  src/client/components/LeftBlueBar/LeftBlueBar.component.js
Labels: frontend

#176 Elevator pitch page
  src/client/assets/images/elevator_man.png
  src/client/components/Elevator/Elevator.component.js
  src/client/components/ElevatorPitchInstructions/ElevatorPitchInstructions.component.js
  src/client/components/ElevatorPitchInstructions/ElevatorPitchInstructions.stories.js
  src/client/components/Pagination/Pagination.styles.css
  src/client/components/RoboModal/RoboModal.component.js
  src/client/components/RoboModal/RoboModal.styles.css
  src/client/containers/ElevatorPitchPage/ElevatorPitchPage.component.js
  src/client/containers/ElevatorPitchPage/ElevatorPitchPage.stories.js
  src/client/containers/ElevatorPitchPage/ElevatorPitchPage.styles.css
Labels: frontend

#182 fix the route inside side menu component
  src/client/components/SideMenu/SideMenu.component.js
Labels: frontend

#185 Fixing the router link issue in the LeftBlueBar component
  src/client/components/LeftBlueBar/LeftBlueBar.component.js
Labels: frontend

#170 added files for users gmail sign/signup with firebase
  src/client/App.js
  src/client/components/Auth/AuthenticatedRoute.component.js
  src/client/components/GoogleLoginButton/GoogleLoginButton.component.js
  src/client/components/GoogleLoginButton/GoogleLoginButton.styles.css
  src/client/components/ProfileBlueBar/ProfileBlueBar.component.js
  src/client/firebase/FirebaseContext.js
  src/client/firebase/GoogleAuth.js
  src/client/firebase/auth.js
  src/client/firebase/config.js
  src/client/hooks/useAuthentication.js
Labels: frontend

#184 Add seed files to production folder
  src/server/seeds/production/01_questions.js
  src/server/seeds/production/02_answers.js
Labels: databases

#188 renamed container folder files acording to the naming guidelines
  src/client/App.js
  src/client/containers/CareerPage/CareerPage.container.js
  src/client/containers/CareerPage/CareerPage.stories.js
  src/client/containers/ElevatorPitchPage/ElevatorPitchPage.container.js
  src/client/containers/ElevatorPitchPage/ElevatorPitchPage.stories.js
  src/client/containers/LoginPage/LoginPage.container.js
  src/client/containers/NextStepsPage/NextStepsPage.container.js
  src/client/containers/NextStepsPage/NextStepsPage.stories.js
  src/client/containers/QuizPage/QuizPage.container.js
  src/client/containers/QuizPage/QuizPage.stories.js
  src/client/containers/QuizResultPage/QuizResultPage.container.js
  src/client/containers/QuizResultPage/QuizResultPage.stories.js
  src/client/containers/RegistrationPage/RegistrationPage.container.js
  src/client/containers/RegistrationPage/RegistrationPage.stories.js
Labels: frontend

#191 added a router for capturing all the invalid routes
  src/client/App.js
Labels: frontend

#192 added cursor for Buttons component and deleted from others
  src/client/components/Buttons/Buttons.component.js
  src/client/components/Buttons/Buttons.styles.css
  src/client/containers/CareerPage/CareerPage.styles.css
  src/client/containers/ElevatorPitchPage/ElevatorPitchPage.styles.css
  src/client/containers/EmptyQuizResultPage/EmptyQuizResultPage.styles.css
Labels: frontend

#193 removed background image to avoid using twice while it should use in …
  src/client/components/ProfileQuizResults/ProfileQuizResults.component.js
Labels: frontend

#196 added cursor for the radio inputs and removed import fonts
  src/client/components/QuizAnswers/QuizAnswers.styles.css
Labels: frontend

#201 Fixed test
  src/client/containers/Home/Home.test.js
Labels: frontend

#187 Question page
  src/client/assets/fonts/fonts.css
  src/client/components/Question/Question.component.js
  src/client/components/QuizAnswers/QuizAnswers.component.js
  src/client/components/QuizAnswers/QuizAnswers.styles.css
  src/client/containers/QuizPage/QuizPage.container.js
  src/server/api/controllers/questions.controller.js
  src/server/api/controllers/users.controller.js
Labels: frontend

#194 Fixed the responsiveness for elevator page
  src/client/components/Elevator/Elevator.styles.css
Labels: frontend

#195 added the files for getting the career and quiz results from the endp…
  src/client/App.js
  src/client/components/ProfileBlueBar/ProfileBlueBar.component.js
  src/client/components/ProfileCareerResult/ProfileCareerResult.component.js
  src/client/components/ProfileQuizResults/ProfileQuizResults.component.js
  src/client/containers/ProfilePage/ProfilePage.container.js
  src/client/containers/ProfilePage/ProfilePage.styles.css
Labels: frontend

#200 i have removed the input fields in the profile component
  src/client/components/ProfileForm/ProfileForm.component.js
  src/client/components/ProfileForm/ProfileForm.stories.js
  src/client/components/ProfileForm/ProfileForm.styles.css
Labels: frontend

#203 fixed child key warning
  src/client/components/CardProfileResult/CardProfileResult.component.js
  src/client/components/JobCard/JobCard.component.js
  src/client/containers/CareerPage/CareerPage.container.js
Labels: frontend

#198 i have deleted the unwanted components
  src/client/App.js
  src/client/components/Forms/Forms.stories.js
  src/client/components/Forms/ResetPassword.js
  src/client/components/Forms/SignIn.js
  src/client/components/Forms/SignUp.js
  src/client/components/Navigation/Header.js
  src/client/components/Success/UserCreationSuccess.js
  src/client/containers/LoginPage/LoginPage.container.js
  src/client/containers/Profile/index.js
  src/client/containers/ResetPassword/ResetPassword.stories.js
  src/client/containers/ResetPassword/index.js
  src/client/containers/SignIn/index.js
  src/client/containers/SignUp/index.js
Labels: frontend

#202 changed button styles in career component
  src/client/containers/CareerPage/CareerPage.styles.css
Labels: frontend

#199 removed dangerouslySetInnerHTML property to fix error in Elevator
  src/client/components/Elevator/Elevator.component.js
  src/client/components/Pagination/Pagination.component.js
  src/client/components/RoboModal/RoboModal.component.js
Labels: frontend

#189 fixed missing link for error,login,elevator pages
  src/client/components/RegisterTeaser/RegisterTeaser.component.js
  src/client/containers/CareerPage/CareerPage.container.js
  src/client/containers/QuizResultPage/QuizResultPage.container.js
Labels: frontend

#190 modified css to get responsive Profile page
  src/client/containers/ProfilePage/ProfilePage.container.js
  src/client/containers/ProfilePage/ProfilePage.styles.css
Labels: frontend

#211 question-image-url-from-other-server
  src/server/seeds/development/01_questions.js
Labels: frontend

#210 removed-2-duplicate-routes
  src/server/api/routes/api-router.js
Labels: backend

#206 Authenticated user can answer questions
  src/client/containers/QuizPage/QuizPage.container.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
Labels: frontend

#212 worked on home-page responsiveness
  src/client/components/DecriptionHome/DescriptionCareer.styles.css
  src/client/containers/Home/Home.container.js
  src/client/containers/Home/Home.styles.css
Labels: frontend

#208 Final question button functionality
  src/client/containers/QuizPage/QuizPage.container.js
Labels: frontend

#204 removed create account from home, and added google logo to login
  src/client/components/LeftBlueBar/LeftBlueBar.component.js
  src/client/components/LeftBlueBar/LeftBlueBar.styles.css
  src/client/containers/Home/Home.styles.css
  src/client/containers/RegistrationPage/RegistrationPage.container.js
  src/client/containers/RegistrationPage/RegistrationPage.styles.css
Labels: frontend

#217 fixed burger menu styles
  src/client/containers/Home/Home.styles.css
Labels: frontend

#213 i have fixed typo mistake in profile page
  src/client/containers/ProfilePage/ProfilePage.container.js
Labels: frontend

#216 Prompt when no answer is selected
  src/client/containers/QuizPage/QuizPage.container.js
  src/client/containers/QuizPage/QuizPage.styles.css
Labels: frontend

#214 changed classnames
  src/client/components/ProfileQuizResults/ProfileQuizResults.styles.css
  src/client/containers/ProfilePage/ProfilePage.styles.css
Labels: frontend

#223 Changed isAgreement question from boolean to number
  src/client/components/QuizAnswers/QuizAnswers.component.js
Labels: frontend

#218 Profile career result changes
  src/client/components/ProfileCareerResult/ProfileCareerResult.component.js
  src/client/components/ProfileCareerResult/ProfileCareerResult.styles.css
Labels: frontend
